spring.application.name=inventory-service


server.servlet.context-path=/api/v1
server.port=9010

#DB
spring.datasource.url=jdbc:postgresql://localhost:5432/inventoryDB
spring.datasource.username=postgres
spring.datasource.password=Sagar@123
spring.jpa.hibernate.ddl-auto=create-drop

#read data from sql file in local
#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=true
#pring.sql.init.data-locations=classpath:data.sql

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true